from typing import List

class Card:
    suit: str
    rank: str
    path_to_image: str
    
    def __init__(self, suit: str, rank: str) -> None: ...
    def __str__(self) -> str: ...
    def value(self) -> int: ...

class Deck:
    cards: List[Card]
    
    def __init__(self) -> None: ...
    def shuffle(self) -> None: ...
    def deal_card(self) -> Card: ...

class Multiple_deck(Deck):
    cards: List[Card]
    
    def __init__(self, num_decks: int = 6) -> None: ...
